# ===== Build Stage =====
FROM node:24-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# บังคับให้ build ใหม่ทุก deploy

ARG VITE_CRYPTO_SECRET_KEY
ARG VITE_API_BASE_URL
ARG VITE_APP_VERSION
ARG VITE_PUBLIC_AUTH_URL
ARG VITE_PUBLIC_CLIENT_ID
ARG VITE_PUBLIC_CALLBACK_URL
ARG VITE_PUBLIC_SCOPE
ARG VITE_PUBLIC_LOGOUT_URL
ARG VITE_PUBLIC_BASICINFO_URL


ENV VITE_CRYPTO_SECRET_KEY=$VITE_CRYPTO_SECRET_KEY
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_PUBLIC_AUTH_URL=$VITE_PUBLIC_AUTH_URL
ENV VITE_PUBLIC_CLIENT_ID=$VITE_PUBLIC_CLIENT_ID
ENV VITE_PUBLIC_CALLBACK_URL=$VITE_PUBLIC_CALLBACK_URL
ENV VITE_PUBLIC_SCOPE=$VITE_PUBLIC_SCOPE
ENV VITE_PUBLIC_LOGOUT_URL=$VITE_PUBLIC_LOGOUT_URL
ENV VITE_PUBLIC_BASICINFO_URL=$VITE_PUBLIC_BASICINFO_URL

RUN echo "CLIENT_ID=$VITE_PUBLIC_CLIENT_ID" \
    && echo "CALLBACK=$VITE_PUBLIC_CALLBACK_URL" \
    && echo "SCOPE=$VITE_PUBLIC_SCOPE"

RUN npm run build

# ===== Runtime Stage =====
FROM nginx:alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /var/www/html
